from __future__ import annotations

import argparse
import json
from pathlib import Path
from statistics import mean
from typing import Dict, List


def _read_json(path: Path) -> Dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt_pct(v: float) -> str:
    return f"{100.0 * v:.1f}%"


def render_dashboard(
    eval_report: Dict | None,
    natural_report: Dict | None,
    ab_report: Dict | None,
) -> str:
    lines: List[str] = []
    lines.append("# VeriLog AI Metrics Dashboard")
    lines.append("")

    if eval_report:
        lines.append("## Model Eval")
        lines.append(
            f"- Accuracy: {_fmt_pct(float(eval_report.get('accuracy', 0.0)))} "
            f"({eval_report.get('correct', 0)}/{eval_report.get('total', 0)})"
        )
        lines.append(f"- Unknown Rate: {_fmt_pct(float(eval_report.get('unknown_rate', 0.0)))}")
        lines.append("")

    if natural_report:
        lines.append("## Natural Bug Sanity Check")
        lines.append(
            f"- Accuracy: {_fmt_pct(float(natural_report.get('accuracy', 0.0)))} "
            f"({natural_report.get('correct', 0)}/{natural_report.get('total', 0)})"
        )
        lines.append(f"- Unknown Rate: {_fmt_pct(float(natural_report.get('unknown_rate', 0.0)))}")
        lines.append("")

    if ab_report:
        lines.append("## A/B Pilot")
        lines.append(f"- Samples: {ab_report.get('samples', 0)}")
        lines.append(f"- Median Manual Minutes: {ab_report.get('manual_p50_min', 0):.2f}")
        lines.append(f"- Median AI Minutes: {ab_report.get('ai_p50_min', 0):.2f}")
        lines.append(f"- P95 Manual Minutes: {ab_report.get('manual_p95_min', 0):.2f}")
        lines.append(f"- P95 AI Minutes: {ab_report.get('ai_p95_min', 0):.2f}")
        lines.append(f"- Median Time Reduction: {_fmt_pct(float(ab_report.get('time_reduction_p50', 0.0)))}")
        lines.append("")

    known = [r for r in [eval_report, natural_report] if r]
    if known:
        lines.append("## Portfolio Health")
        avg_acc = mean([float(r.get("accuracy", 0.0)) for r in known])
        lines.append(f"- Mean Accuracy Across Available Reports: {_fmt_pct(avg_acc)}")
        lines.append("")

    lines.append("_Generated by `python -m metrics.dashboard`._")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate markdown dashboard from metrics artifacts")
    parser.add_argument("--eval-report", default="reports/eval_report.json")
    parser.add_argument("--natural-report", default="reports/natural_bug_report.json")
    parser.add_argument("--ab-report", default="reports/ab_test_report.json")
    parser.add_argument("--out", default="reports/dashboard_summary.md")
    args = parser.parse_args()

    eval_report = _read_json(Path(args.eval_report)) if Path(args.eval_report).exists() else None
    natural_report = (
        _read_json(Path(args.natural_report)) if Path(args.natural_report).exists() else None
    )
    ab_report = _read_json(Path(args.ab_report)) if Path(args.ab_report).exists() else None

    summary = render_dashboard(eval_report, natural_report, ab_report)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(summary, encoding="utf-8")
    print(f"Wrote dashboard summary to {out_path}")


if __name__ == "__main__":
    main()
